# Generated by Django 6.0.3 on 2026-04-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('ngram_title', 'Ngram Title'), ('user_query', 'User Query')], max_length=16)),
                ('weight', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-weight'], name='search_sear_source_a79ecd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('result_slug', models.CharField(max_length=255)),
                ('result_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='accounts.child')),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='search_sear_created_4a70e7_idx')],
            },
        ),
    ]
