# Generated by Django 6.0.3 on 2026-07-27 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_loginlockout_passwordsetuptoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('part_of_day', models.CharField(choices=[('pagi', 'Pagi'), ('siang', 'Siang'), ('sore', 'Sore'), ('malam', 'Malam')], max_length=8)),
                ('kind', models.CharField(choices=[('routine', 'Rutin'), ('once', 'Sekali')], max_length=8)),
                ('repeat_days', models.JSONField(blank=True, default=list)),
                ('date', models.DateField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to='accounts.child')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='schedule.scheduletask')),
            ],
            options={
                'unique_together': {('task', 'date')},
            },
        ),
    ]
