# Generated by Django 6.0.3 on 2026-08-04 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='englishlesson',
            name='audio_status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('ready', 'Siap'), ('failed', 'Gagal')], default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='englishlesson',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='englishlesson',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='englishlesson',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='englishsegment',
            name='audio',
            field=models.FileField(blank=True, upload_to='english/segments/'),
        ),
    ]
