# Generated by Django 6.0.3 on 2026-08-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_englishlesson_audio_status_englishlesson_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWeakPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneme', models.CharField(max_length=8)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('pass_streak', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('tracking', 'Dipantau'), ('active', 'Perlu latihan'), ('cleared', 'Lulus')], default='tracking', max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_weakpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fail_count', 'phoneme'],
                'unique_together': {('owner', 'phoneme')},
            },
        ),
    ]
