# Generated by Django 6.0.3 on 2026-08-04 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_englishstreak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWordPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('pass_streak', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('tracking', 'Dipantau'), ('active', 'Perlu latihan'), ('cleared', 'Lulus')], default='tracking', max_length=10)),
                ('manual', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fail_count', 'word'],
                'unique_together': {('owner', 'word')},
            },
        ),
    ]
