# Generated by Django 6.0.3 on 2026-08-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_englishwordpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishDictEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('ipa', models.CharField(blank=True, max_length=128)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('found', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
