# Generated by Django 6.0.3 on 2026-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_seed_post_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readreceipt',
            name='first_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
