# Generated by Django 6.0.3 on 2026-07-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_readreceipt_first_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_username', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
