# Generated by Django 6.0.3 on 2026-07-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diaryconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryConfig',
        ),
    ]
