# Generated by Django 6.0.3 on 2026-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_delete_diaryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
