# Generated by Django 6.0.3 on 2026-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_post_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
