# Generated by Django 6.0.3 on 2026-03-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('coin_cost', models.PositiveIntegerField(default=1)),
                ('session_minutes', models.PositiveIntegerField(default=5)),
                ('bundle', models.FileField(upload_to='games/bundles/')),
                ('bundle_version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('category', models.CharField(choices=[('arcade', 'Arcade'), ('puzzle', 'Puzzle / Kata'), ('math', 'Matematika'), ('creative', 'Kreativitas'), ('islamic', 'Islami'), ('reaction', 'Reaksi')], default='arcade', max_length=20)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='accounts.child')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
            ],
        ),
    ]
