# Generated by Django 6.0.3 on 2026-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_add_timeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='source_device',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
