# Generated by Django 6.0.3 on 2026-03-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reading', '0003_readingprogress_source_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField()),
                ('source_device', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to='accounts.child')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
