# Generated by Django 6.0.3 on 2026-06-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_reference', models.CharField(max_length=100)),
                ('day_threshold', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_reading_date', models.DateField(blank=True, null=True)),
                ('grace_period_end_date', models.DateField(blank=True, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streaks', to='streaks.badge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='accounts.child')),
            ],
            options={
                'unique_together': {('child',)},
            },
        ),
    ]
