# Generated by Django 6.0.3 on 2026-06-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('streaks', '0002_seed_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('reading_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_keys', to='accounts.child')),
            ],
            options={
                'unique_together': {('key', 'child')},
            },
        ),
    ]
