# Generated by Django 6.0.3 on 2026-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='source_device',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='voided_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='type',
            field=models.CharField(choices=[('coin', 'Coin'), ('star', 'Star'), ('coin_adjustment', 'Coin Adj'), ('star_adjustment', 'Star Adj')], max_length=20),
        ),
    ]
