# Generated by Django 6.0.3 on 2026-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewardhistory_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardhistory',
            name='type',
            field=models.CharField(choices=[('coin', 'Coin'), ('star', 'Star'), ('coin_adjustment', 'Coin Adj'), ('star_adjustment', 'Star Adj'), ('coin_spend', 'Coin Spend')], max_length=20),
        ),
    ]
