# Generated by Django 6.0.3 on 2026-04-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('queue_depth_rewards', models.PositiveIntegerField(default=0)),
                ('queue_depth_progress', models.PositiveIntegerField(default=0)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_telemetry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
